/**
 * Demo Responses
 * 
 * Comprehensive mock data for DEMO mode.
 * All AI endpoints return simulated responses from this file.
 */

export const DEMO_RESPONSES: Record<string, any> = {
  'ai/research-brief': {
    brief: `[DEMO] Research Brief Generated
    
Topic: Impact of Telemedicine on Chronic Disease Management
Study Design: Retrospective Cohort
Time Period: 2020-2024

Suggested Refinements:
- Consider socioeconomic confounders
- Address selection bias in telemedicine adoption
- Plan for ~15% missing data in A1C values

This is a simulated response. In LIVE mode, this would be generated by AI based on your actual topic declaration.`,
    mode: 'DEMO',
    timestamp: new Date().toISOString(),
  },
  
  'ai/literature-search': {
    results: [
      { id: 1, title: '[DEMO] Sample Study on Telemedicine Outcomes', year: 2024, citations: 45, authors: 'Smith et al.', journal: 'JAMA' },
      { id: 2, title: '[DEMO] Meta-analysis of Remote Patient Monitoring', year: 2023, citations: 128, authors: 'Johnson et al.', journal: 'NEJM' },
      { id: 3, title: '[DEMO] Comparative Effectiveness Research Methods', year: 2023, citations: 89, authors: 'Williams et al.', journal: 'Lancet' },
      { id: 4, title: '[DEMO] Digital Health Interventions Review', year: 2024, citations: 32, authors: 'Brown et al.', journal: 'BMJ' },
      { id: 5, title: '[DEMO] Chronic Disease Self-Management Tools', year: 2023, citations: 67, authors: 'Davis et al.', journal: 'Annals IM' },
    ],
    totalResults: 156,
    message: 'In LIVE mode, this would search PubMed and Semantic Scholar',
    mode: 'DEMO',
  },
  
  'phi/scan': {
    status: 'PASS',
    detected: [],
    scannedItems: 24,
    scanDuration: '1.2s',
    message: '[DEMO] PHI scan simulation - no real data processed',
    mode: 'DEMO',
  },
  
  'phi/scan-fail': {
    status: 'FAIL',
    detected: [
      { type: 'SSN', location: 'row 15, column C', confidence: 0.95 },
      { type: 'DOB', location: 'row 22, column D', confidence: 0.89 },
    ],
    scannedItems: 24,
    scanDuration: '1.4s',
    message: '[DEMO] PHI detected - this is simulated data',
    mode: 'DEMO',
  },
  
  'ai/manuscript-draft': {
    sections: {
      introduction: `[DEMO] Introduction
      
Telemedicine has emerged as a transformative approach to healthcare delivery, particularly for managing chronic diseases. This study examines the impact of telemedicine interventions on clinical outcomes in patients with diabetes, hypertension, and heart failure during the period 2020-2024.

This section would be AI-generated in LIVE mode based on your literature review and study design.`,
      methods: `[DEMO] Methods

Study Design: Retrospective cohort study using electronic health records from 12 healthcare systems.

Population: Adults aged 18+ with established chronic disease diagnoses who received telemedicine services.

Outcomes: Primary - HbA1c reduction, blood pressure control, heart failure hospitalization rates.

This section would reflect your actual SAP in LIVE mode.`,
      results: `[DEMO] Results

A total of 45,678 patients met inclusion criteria. Mean age was 58.3 years (SD 12.4), and 52% were female.

Primary Outcomes:
- HbA1c reduction: -0.6% (95% CI: -0.7 to -0.5)
- BP control improvement: 12.3% absolute increase
- HF hospitalization reduction: OR 0.78 (95% CI: 0.65-0.94)

This section would contain your actual analysis outputs in LIVE mode.`,
      discussion: `[DEMO] Discussion

Our findings suggest telemedicine is associated with improved chronic disease outcomes across multiple conditions. These results align with prior literature while providing novel insights into real-world effectiveness.

Limitations include potential selection bias and the observational study design.

This section would synthesize your actual findings in LIVE mode.`,
    },
    wordCount: 2456,
    figureCount: 4,
    tableCount: 3,
    mode: 'DEMO',
  },
  
  'ai/statistical-analysis': {
    completed: true,
    outputs: {
      primaryAnalysis: '[DEMO] Logistic regression model fitted',
      sensitivityAnalyses: '[DEMO] 3 sensitivity analyses completed',
      subgroupAnalyses: '[DEMO] 5 subgroup analyses completed',
    },
    metrics: {
      pValue: 0.023,
      effectSize: 0.34,
      confidenceInterval: [0.21, 0.47],
    },
    mode: 'DEMO',
  },
  
  'ai/topic-refinement': {
    refinedTopic: '[DEMO] Comparative Effectiveness of Synchronous vs. Asynchronous Telemedicine for Type 2 Diabetes Management in Underserved Populations',
    suggestions: [
      'Consider narrowing to specific age groups',
      'Add health equity dimension',
      'Include patient satisfaction outcomes',
    ],
    feasibilityScore: 0.85,
    mode: 'DEMO',
  },
  
  'governance/approvals': {
    pending: [
      { id: 'demo-1', operation: 'DATA_EXPORT', requestedBy: 'demo@example.com', requestedAt: new Date().toISOString() },
      { id: 'demo-2', operation: 'LLM_CALL', requestedBy: 'demo@example.com', requestedAt: new Date().toISOString() },
    ],
    mode: 'DEMO',
  },
  
  'governance/audit-log': {
    entries: [
      { id: 'audit-1', action: 'VIEW_DATA', user: 'demo@example.com', timestamp: new Date().toISOString(), details: 'Viewed synthetic dataset' },
      { id: 'audit-2', action: 'RUN_ANALYSIS', user: 'demo@example.com', timestamp: new Date().toISOString(), details: 'Ran demo statistical analysis' },
      { id: 'audit-3', action: 'GENERATE_DRAFT', user: 'demo@example.com', timestamp: new Date().toISOString(), details: 'Generated demo manuscript section' },
    ],
    mode: 'DEMO',
  },
};

/**
 * Get a demo response for a given endpoint
 */
export function getDemoResponse(endpoint: string): any {
  const response = DEMO_RESPONSES[endpoint];
  if (response) {
    return {
      success: true,
      mode: 'DEMO',
      data: response,
    };
  }
  return {
    success: true,
    mode: 'DEMO',
    data: { message: 'Demo response - this would contain real data in LIVE mode' },
  };
}
